# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Source Data Journalism
email: your-email@domain.com
description: |
  How data journalists open source the reproducable data, analyses, and code behind their data stories. By Christine Zhang and Dan Nguyen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://opensourcedatajournalism.github.io" # the base hostname & protocol for your site
github_username: opensourcedatajournalism

# Build settings
markdown: kramdown
